import { AirVent, AlarmSmoke, Bath, BedDouble, Book, Bubbles, Camera, ChefHat, ChessQueen, Coffee, CookingPot, Heater, Microwave, Refrigerator, SoapDispenserDroplet, SquareParking, Table, ThermometerSun, Tv, WashingMachine, WavesLadder, Wifi } from "lucide-react";

export const amenitiesIcon = {
    "bathub": Bath,
    "cleaning-products": Bubbles,
    "hot-water": ThermometerSun,
    "washer": WashingMachine,
    "essentials": SoapDispenserDroplet,
    "bed-linens": BedDouble,
    "books": Book,
    "board-games": ChessQueen,
    "central-heating": Heater,
    "smoke-alarm": AlarmSmoke,
    "wifi": Wifi,
    "kitchen": ChefHat,
    "refrigerator": Refrigerator,
    "microwave": Microwave,
    "cooking-basics": CookingPot,
    "coffee": Coffee,
    "dining-table": Table,
    "climatisation": AirVent,
    "television": Tv,
    "camera": Camera,
    "parking": SquareParking,
    "pool": WavesLadder,
} as Record<string, any>