import { AlarmIcon, BathtubIcon, BedIcon, BookIcon, CameraIcon, CheckerboardIcon, ChefHatIcon, CoffeeIcon, CookingPotIcon, DropIcon, FanIcon, HandSoapIcon, LetterCirclePIcon, OvenIcon, ParkIcon, SwimmingPoolIcon, TableIcon, TelevisionIcon, ThermometerColdIcon, ThermometerHotIcon, ThermometerIcon, WashingMachineIcon, WifiHighIcon } from "@phosphor-icons/react";

export const amenitiesIcon = {
    "bathub": BathtubIcon,
    "cleaning-products": DropIcon,
    "hot-water": ThermometerHotIcon,
    "washer": WashingMachineIcon,
    "essentials": HandSoapIcon,
    "bed-linens": BedIcon,
    "books": BookIcon,
    "board-games": CheckerboardIcon,
    "central-heating": ThermometerIcon,
    "smoke-alarm": AlarmIcon,
    "wifi": WifiHighIcon,
    "kitchen": ChefHatIcon,
    "refrigerator": ThermometerColdIcon,
    "microwave": OvenIcon,
    "cooking-basics": CookingPotIcon,
    "coffee": CoffeeIcon,
    "dining-table": TableIcon,
    "climatisation": FanIcon,
    "television": TelevisionIcon,
    "camera": CameraIcon,
    "parking": LetterCirclePIcon,
    "pool": SwimmingPoolIcon,
} as Record<string, any>