services:
  db:
    image: postgres:18.3
    container_name: bookaway_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: bookaway
    ports:
      - "5439:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
